apiVersion: v1
kind: Service
metadata:
  name: myproject-calculator-service
spec:
  selector:
    app: myproject-calculator-service
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 5000